version: "3.7"

services:
  backend:
    image: registry.bjarke.xyz/shoppinglistv4-backend
    build:
      context: ./
    deploy:
      replicas: 2
    networks:
      - shoppinglistv4
      - swarm-overlay
      - postgres

networks:
  postgres:
    external: true
    name: postgres_prod_postgres-prod
  shoppinglistv4:
    driver: overlay
  swarm-overlay:
    external: true
    name: swarm-overlay
