version: "3.7"

services:
  backend:
    image: registry.bjarke.xyz/shoppinglistv4-backend
    build:
      context: ./
    deploy:
      replicas: 2
    networks:
      - shoppinglistv4
      - swarm-overlay
      - postgres

  migrate:
    image: registry.bjarke.xyz/shoppinglistv4-backend
    entrypoint: /shoppinglist-backend-migrate -migrate up
    deploy:
      replicas: 0
      restart_policy:
        condition: none
    build:
      context: ./
    networks:
      - shoppinglistv4
      - postgres
networks:
  postgres:
    external: true
    name: postgres_prod_postgres-prod
  shoppinglistv4:
    driver: overlay
  swarm-overlay:
    external: true
    name: swarm-overlay
