version: "3.7"

services:
  backend:
    image: registry.bjarke.xyz/shoppinglist-backend
    build:
      context: ./
    deploy:
      replicas: 2
    secrets:
      - env
    networks:
      - swarm-overlay

  worker:
    image: registry.bjarke.xyz/shoppinglist-backend
    entrypoint: /shoppinglist-backend-worker
    build:
      context: ./
    deploy:
      replicas: 2
    secrets:
      - env
    networks:
      - swarm-overlay

networks:
  swarm-overlay:
    external: true
    name: swarm-overlay

secrets:
  env:
    file: .env
