version: "3.7"

services:
  backend:
    image: registry.bjarke.xyz/shoppinglistv4-backend
    build:
      context: ./
    deploy:
      replicas: 2
    networks:
      - shoppinglistv4
      - swarm-overlay

  worker:
    image: registry.bjarke.xyz/shoppinglistv4-backend
    entrypoint: /shoppinglist-backend-worker
    build:
      context: ./
    deploy:
      replicas: 2
    networks:
      - shoppinglistv4
      - swarm-overlay

  redis:
    image: redis:alpine
    networks:
      - shoppinglistv4

networks:
  shoppinglistv4:
    driver: overlay
  swarm-overlay:
    external: true
    name: swarm-overlay
