-- Add UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS items (
  id UUID DEFAULT uuid_generate_v4 () PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NULL,
  deleted_at TIMESTAMP WITH TIME ZONE NULL,
  owner_id VARCHAR(36) NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS lists (
  id UUID DEFAULT uuid_generate_v4 () PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NULL,
  deleted_at TIMESTAMP WITH TIME ZONE NULL,
  owner_id VARCHAR(36) NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS default_lists (
  id UUID DEFAULT uuid_generate_v4 () PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NULL,
  app_user_id VARCHAR(36) NOT NULL,
  list_id UUID REFERENCES lists (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS list_item (
  id UUID DEFAULT uuid_generate_v4 () PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NULL,
  list_id UUID REFERENCES lists (id) ON DELETE CASCADE,
  item_id UUID REFERENCES items (id) ON DELETE CASCADE,
  crossed BOOLEAN NOT NULL DEFAULT FALSE
);
